### PR TITLE
Added Sidebar Fileicons

### PR DESCRIPTION
**Pull request by marcofugaro**
Added fileicons in the sidebar in all the themes, on default they are hidden and you can enable them with the setting `spacegray_fileicons: true`.

Discussion in issue #128 

I took the folder icons from Cyanyde theme, and the other icons from various other themes.

The icons that are okay but these could use some graphic tweaks are: 
- ~~pdf (is white)~~
- ~~list (is white)~~
- ~~python (give it the python colors)~~
- ~~spinner (make it round?)~~

Overall all good.

EDIT: ~~need some testing on Mac before I can pull this in, any help is appreciated!~~

EDIT2: Done all the stuff that needed to be done!

### CODE REVIEW

**Comment by arjunkharbanda** [comment]
unable to enable file icons

**Comment by marcofugaro** [comment]
Did you download from the branch `betterfileicons` and then pasted it in the right place?

Also you need to put `spacegray_fileicons: true` in your sublime settings.

**Comment by arjunkharbanda** [comment]
I was unaware of downloading part. Can you guide me please

**Comment by marcofugaro** [comment]
Here

https://github.com/marcofugaro/spacegray/tree/betterfileicons#manual

**Comment by arjunkharbanda** [comment]
thanks man. and please tell me how to enable this open files tab in sidebar as shown in screen shot

spacegray-eighties

**Comment by marcofugaro** [comment]
closing in favor of #185

**Comment by nhaglind** [comment]
Installed latest version via package control and sidebar icons missing even though user preferences contain `"spacegray_fileicons": true`

**Comment by marcofugaro** [comment]
Bumped the version, now the package should update automatically.

**Comment by folkrav** [comment]
Same as @nhaglind, fresh install through Package Control, `"spacegray_fileicons": true` in user settings, still no sidebar icons.

**Comment by marcofugaro** [comment]
it needs to be updated to 1.3.0 on PackageControl
https://packagecontrol.io/packages/Theme%20-%20Spacegray
Pinging the man himself @kkga

**Comment by marcofugaro** [comment]
@folkrav ok update should be rolling out now

**Pull request closed without merging**
