### PR TITLE
update `Spacegray` to support sidebar icons

### PR DESCRIPTION
**Pull request by kurtextrem**
Icons are from default / Soda / a download from a user of the sublime text
forum.

Note: My Sublime Text messed up with tabs and spaces (at least I think so), but the only things I've changed are starting after the "sidebar group open" ending before "STANDARD TEXT BUTTONS". The 3 groups on the very bottom to "fix" an issue were removed as well. Best is to reindent or copy my changes I guess.

Edit: Another change: https://github.com/kkga/spacegray/pull/129/files#diff-9d824ee2f566389f0300495f2fc2745fR750, it makes the search bar look quite nicely :)

### CODE REVIEW

**Comment by lpommers** [comment]
I would love to see this become a part of the theme

**Comment by buildersbrewery** [comment]
Any updates on this? Will this be merged or will you rather add icons like they can be found in [ctf0/Seti_ST3](/ctf0/Seti_ST3) ?

/cc @kkga @gaearon

**Comment by jrappen** [comment]
Could you add the missing file to fix this pr? @kurtextrem

**Comment by kurtextrem** [comment]
I had to reset my laptop and therefore don't have that anymore.

**Comment by marcofugaro** [comment]
closing in favor of #185

**Pull request closed without merging**
